### PR TITLE
Route /tokens, avoid crashing page 

### LINKED ISSUE #56: Route /token, TypeError: Cannot read property 'map' of undefined
When a user tries to open this route sometimes the page throw the following error, 

````
VM10477 BoxToken.tsx:20 Uncaught (in promise) TypeError: Cannot read property 'map' of undefined
    at exports.BoxToken.props (VM10477 BoxToken.tsx:20)
    at eval (ReactCompositeComponent.js:303)
    at measureLifeCyclePerf (ReactCompositeComponent.js:73)
    at ReactCompositeComponentWrapper._constructComponentWithoutOwner (ReactCompositeComponent.js:302)
    at ReactCompositeComponentWrapper._constructComponent (ReactCompositeComponent.js:277)
    at ReactCompositeComponentWrapper.mountComponent (ReactCompositeComponent.js:185)
    at Object.mountComponent (ReactReconciler.js:43)
    at ReactDOMComponent.mountChildren (ReactMultiChild.js:234)
    at ReactDOMComponent._createInitialChildren (ReactDOMComponent.js:701)
    at ReactDOMComponent.mountComponent (ReactDOMComponent.js:520)
```

### PR DESCRIPTION
**Pull request by wzalazar**
This PR introduces,

- Sets default value to ```apiTokens```

fix #56

### CODE REVIEW

File: src/components/atoms/BoxToken/BoxToken.tsx [hunk 1]
```diff
@@ -107,11 +111,11 @@ export const BoxToken = (props: BoxTokenProps): JSX.Element => (
         </tr>
       </thead>
       <tbody>
-        {props.apiTokens
+        {apiTokens
```
Comment (lautarodragan) [inline src/components/atoms/BoxToken/BoxToken.tsx]: Just curious - couldn't this have been fixed by duck typing? Like just changing this line to `apiTokens && apiTokens.length && apiTokens.map...`

Comment (wzalazar) [reply src/components/atoms/BoxToken/BoxToken.tsx]: yes, it works. But I prefer to avoid unnecessary logic.

What do you prefer?

Comment (lautarodragan) [reply src/components/atoms/BoxToken/BoxToken.tsx]: LGTM
